[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
whirpool_v1 = "6Zx9KWVKQQkqryW2UrbHinTYTGeTrvH7jG1YTe6SRMGR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster  = "https://api.mainnet-beta.solana.com"
wallet = "/home/gcordova/dev_env/test_solana/orca_prb_1/app/account/ACC_1.json"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"


